TECHNOLOGY("RTFlyingFreight"):remove_prereq("logistics-2")
TECHNOLOGY("RTMagnetTrainRamps"):remove_pack("chemical-science-pack"):remove_pack("py-science-pack-2")
TECHNOLOGY("RTDeliverThePayload"):remove_pack("chemical-science-pack"):remove_pack("py-science-pack-2"):remove_prereq('military-3'):remove_pack("military-science-pack")
RECIPE("RTMagnetTrainRampRecipe"):replace_ingredient("advanced-circuit", "electronic-circuit")
TECHNOLOGY("EjectorHatchRTTech"):remove_pack("logistic-science-pack"):remove_pack("py-science-pack-1")
TECHNOLOGY("RTSimonSays"):remove_prereq("advanced-electronics"):remove_pack("logistic-science-pack"):remove_pack("py-science-pack-1"):add_prereq("vacuum-tube-electronics")
TECHNOLOGY("RTFlyingFreight"):add_prereq("logistic-science-pack")
TECHNOLOGY("RTZiplineTech2"):remove_pack("logistic-science-pack"):remove_pack("py-science-pack-1")
TECHNOLOGY("RTZiplineTech3"):remove_pack("chemical-science-pack")
TECHNOLOGY("RTZiplineTech4"):add_pack("py-science-pack-3")
TECHNOLOGY("RTZiplineTech5"):remove_pack("py-science-pack-4"):remove_pack("utility-science-pack")
TECHNOLOGY("SignalPlateTech"):remove_pack("logistic-science-pack")
TECHNOLOGY("RTProgrammableZiplineControlTech"):remove_pack("logistic-science-pack")
RECIPE("DirectorBouncePlateRecipie"):replace_ingredient("advanced-circuit", "electronic-circuit")
